### PR TITLE
Introduce github-workflow and upgrade to newer python/pypy

### PR DESCRIPTION
**Pull request by aurzenligl**
Quick and dirty attempt to get github workflow up and running after finding out in horror that travis isn't free (as beer) anymore.

Aimed to unblock: https://github.com/aurzenligl/prophy/pull/35

### CODE REVIEW

**Comment by aurzenligl** [comment]
@kamichal, @florczakraf - consider reviewing changes in this PR, there were changes needed to account for change from paid travis to free github-workflows, python/pypy/gcc/clang/waf upgrades required fixes here and there.

**Comment by aurzenligl** [comment]
Let's just merge it.

**Comment by kamichal** [comment]
Very nice, I like it. Thanks!

**Comment by kamichal** [comment]
The badge with python versions in readme index is not updated (max py36).

**Comment by aurzenligl** [comment]
It should update itself when I release a patch -> let me do that in the evening.

**Pull request merged**
