### PR TITLE
Add tests coverage for python 3.7-3.10 and pypy3.

### PR DESCRIPTION
**Pull request by kamichal**
OK, seems that `prophy` works well even with `python3.10` and `pypy3`. Just the tests needed to be adjusted a bit because of the newer clang behavior.

### CODE REVIEW

**Comment by kamichal** [comment]
Seems that Travis is not with us anymore. ...or I miss something. Where's the CI?
BTW, greetings from Tampere.

**Comment by florczakraf** [comment]
Doesn't Travis require project owner to link the accounts and select projects to run there? @aurzenligl 

Or perhaps it might be the time to migrate on to Github Actions

**Comment by aurzenligl** [comment]
Hey, I just visited the PR, let me check the CI :sweat_smile:

**Comment by aurzenligl** [comment]
It seems migration from old travis to new travis service is needed...

https://travis-ci.org/github/aurzenligl/prophy
->
https://www.travis-ci.com/aurzenligl/prophy

**Comment by aurzenligl** [comment]
https://docs.travis-ci.com/user/billing-overview/#free-trial-plan
whoops, free trial plan is available once, only for new users, and they need my credit card number. Hmm, let's explore what Github has to offer instead in terms of CI

**Comment by aurzenligl** [comment]
I'll try to create a PR adding support for github workflow today, or fail miserably and continue tomorrow.

**Comment by aurzenligl** [comment]
So far so good, it's enough to add workflow file and github automagically starts tests for PR-s: https://github.com/aurzenligl/prophy/pull/36
image
I need to make this github workflow pass tests (install proper dependencies for running gtest, etc.), which I'll do tomorrow - and merge #36 before this PR can be merged. I also need to figure out how to connect github workflow coveralls.io (previously travis uploaded stuff there). Let me know what you think @kamichal and @florczakraf.

**Review by aurzenligl — COMMENTED** [review]
https://github.com/aurzenligl/prophy/pull/36 seems to be passing tests, I need to rebase all those wip commits to clear history... perhaps I'll simply include this PR into #36. I'll continue tomorrow.

**Comment by aurzenligl** [comment]
I believe I merged all changes from this PR to https://github.com/aurzenligl/prophy/pull/36, let's close this one in favor of it.

**Pull request closed without merging**
